name: Aggiorna Palinsesto
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Esegui generatore
        run: python generatore.py
      - name: Salva modifiche su GitHub
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m "Aggiornamento automatico index.html" || exit 0
          git push
