name: Aggiornamento Palinsesto Quant

on:
  schedule:
    # Esegue lo script ogni giorno alle 07:00 UTC
    - cron: '0 7 * * *'
  workflow_dispatch: # Permette anche l'esecuzione manuale da GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: pip install requests

      - name: Esegui generatore
        env:
          API_KEY: ${{ secrets.THE_ODDS_API_KEY }}
        run: python main.py

      - name: Commit e Push delle modifiche
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m "Autoupdate palinsesto quant" || exit 0
          git push
